### ISSUE TITLE
Bitcoin Core not installed

### ISSUE THREAD

**Issue by artemkkk** [BlockchainCommons/Bitcoin-Standup-MacOS#10]
<img width="459" alt="Screenshot 2020-05-18 at 13 22 17" src="https://user-images.githubusercontent.com/8707649/82202625-dcb82600-990a-11ea-935e-a23e4f7a1653.png">

After some period of standby (I'm using the setup for evaluation purposes and non-regularly), StandUp stopped seeing Bitcoin core, nor suggesting installing it, neither finding/updating config. I've rechecked the $path in StandUp settings - it's ok, bitcoin.conf & rpccredentials in place along with Bitcoin Core itself and blocks.
As an experiment tried to apply strap.sh again, and replace StandUp.the app itself (clean install), launch bitcoind manually, still the same result..
I believe there is something very simple I'm missing

**Comment by artemkkk** [comment]
Ok, finally I've revealed that the "StandUp" button is devoted to the re-installation of btcore. Pure UX glitch, worths to fix.
However, that was not perfect to re-install and it would be great to learn what was wrong and why it was not fixable manually.
I've also revealed some minor things that might worth to fix somewhere, like path shown while the installation is different from the settings, etc..

**Comment by Fonta1n3** [comment]
Sorry, only just seeing this now. The best thing to do is locate your Standup directory which is what the app creates when "standing up". It is located at`~/StandUp`.

Try deleting that directory (or using the `Stand Down` button in settings) and then using the StandUp button again. It will *not* delete any blockchain data or interfere with your config but will start StandUp fresh and give you the latest Bitcoin Core and should resolve your issue. 

Which path was incorrect? There are multiple paths being used. One is the StandUp path as noted above which just holds the binaries and signatures for Bitcoin Core the other path is for your conf and another path for the blockchain data.

**Comment by Fonta1n3** [comment]
Looks like I am getting the same issue. I will fix it now, seems to be a glitch when there is a newer version of Bitcoin Core available. Thanks for the issue.

**Comment by Fonta1n3** [comment]
@artemkkk This was fixed in this #13 

Please do git clone this PR and keep testing :) it would be very helpful! Thanks.
